language: ruby
sudo: false
before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.2.2
  - ruby-head
  - rbx-2
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-head
  fast_finish: true
bundler_args: --without test
branches:
  only:
    - master
