language: ruby
sudo: false
rvm:
  - 2.2.2
  - ruby-head
  - rbx-2
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-head
  fast_finish: true
branches:
  only:
    - master
